# Generated by Django 5.0.6 on 2024-05-19 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Id', models.CharField(max_length=10)),
                ('Userame', models.CharField(max_length=10)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
    ]
