# Generated by Django 5.0.6 on 2024-07-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
