# Generated by Django 5.0.6 on 2024-08-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=50)),
                ('chart_name', models.CharField(max_length=100)),
                ('chart_data', models.TextField()),
                ('available', models.BooleanField(default=True)),
                ('create_id', models.IntegerField()),
                ('modify_id', models.IntegerField()),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(auto_now=True)),
                ('branch_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FrontendSpecificModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'frontend_specific_model',
            },
        ),
    ]
