# Generated by Django 5.0.6 on 2024-08-05 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0002_chartdata_frontendspecificmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartdata',
            name='name',
            field=models.CharField(default='Default Chart Name', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='chart_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='chartdata',
            table='charts',
        ),
    ]
