# Generated by Django 5.0.6 on 2024-07-15 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0002_alter_module_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rolepermission',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
