# Generated by Django 3.2 on 2024-06-22 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0002_alter_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='0000000000', max_length=15, unique=True),
        ),
    ]
