# Generated by Django 3.2 on 2024-06-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0004_auto_20240624_0230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='expiry_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
