# Generated by Django 3.2 on 2024-06-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0006_alter_user_verification_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_secret',
            field=models.CharField(blank=True, default=None, max_length=16, null=True),
        ),
    ]
