# Generated by Django 5.0.6 on 2024-07-08 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0010_user_date_joined'),
    ]

    operations = [
    ]
