# Generated by Django 5.0.6 on 2024-07-09 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0014_alter_rolepermission_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='permission_name',
            field=models.CharField(default=False, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission_name')},
        ),
    ]
