# Generated by Django 5.0.6 on 2024-07-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0015_alter_rolepermission_permission_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_query',
            field=models.BooleanField(default=False),
        ),
    ]
