# Generated by Django 5.0.6 on 2024-07-10 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app113209', '0017_role_is_active_role_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='module',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
